# Dockerfile.api
FROM python:3.11.5-slim-bullseye

WORKDIR /app/api

COPY requirements_api.txt .
RUN pip install --no-cache-dir -r requirements_api.txt

COPY api/ .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8100"]
