version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8100:8100"
    environment:
      - DB_HOST=172.17.0.1
      - DB_PORT=5434
      - DB_NAME=vv8_backend
      - DB_USER=vv8
      - DB_PASSWORD=vv8
      - DB_WRITE_MODE=immediate
      - DROP_TABLE=false
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE=job_queue
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - static_analysis_network_3

  worker:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.worker
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DB_HOST=172.17.0.1
      - DB_PORT=5434
      - DB_NAME=vv8_backend
      - DB_USER=vv8
      - DB_PASSWORD=vv8
      - DB_WRITE_MODE=immediate
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE=job_queue
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - static_analysis_network_3
    volumes:
      - graphs:/app/worker/graphs

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5762:5672"
      - "15672:15672"
    privileged: true
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - static_analysis_network_3
    volumes:
      - rabbit_mq_home:/var/lib/rabbitmq

  # promtail:
  #   image: grafana/promtail:3.4.1
  #   volumes:
  #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - promtail_home:/mnt/config
  #   command: -config.file=/mnt/config/promtail-config.yaml
  #   networks:
  #     - static_analysis_network_3

networks:
  static_analysis_network_3:
    name: custom_static_analysis_network_8
    driver: bridge

volumes:
  # promtail_home:
  #   driver: local
  #   driver_opts:
  #     type: nfs
  #     o: addr=172.19.156.24,rw
  #     device: ":/home/a8tariq/BehavioralBiometricSA/static_analysis/promtail"
  rabbit_mq_home:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.19.156.24,rw
      device: ":/home/a8tariq/BehavioralBiometricSA/static_analysis/rabbit_mq"
  graphs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.19.156.24,rw
      device: ":/home/a8tariq/BehavioralBiometricSA/static_analysis/worker/graphs"
    